/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author After
 */
public class VentasForm extends javax.swing.JFrame {

    /**
     * Creates new form VentasForm
     */
    
    static int caso;
    public VentasForm(int x) {
        caso = x;
        initComponents();
        switch (caso){
            case 1:
                btnEliminar.setVisible(false);
                btnBuscar.setVisible(false);
                btnBuscarH.setVisible(true);
                btnAñadir.setVisible(true);
                btnGuardarH.setVisible(false);
                btnGuardar.setVisible(false);
                
                txtFecha.setEnabled(false);
                txtCantidad.setEnabled(false);
                txtSubtotal.setEnabled(false);
                txtVentaH.setEnabled(true);
                txtCliente.setEnabled(false);
                txtProductos.setEnabled(false);
                txtVenta.setEnabled(false);
                txtEmpleado.setEnabled(false);
                txtPrecio.setEnabled(false);
                
                break;
            case 2:
                btnEliminar.setVisible(false);
                btnBuscar.setVisible(false);
                btnBuscarH.setVisible(true);
                btnAñadir.setVisible(false);
                btnGuardarH.setVisible(false);
                btnGuardar.setVisible(false);
                
                txtFecha.setEnabled(false);
                txtCantidad.setEnabled(false);
                txtSubtotal.setEnabled(false);
                txtVentaH.setEnabled(true);
                txtCliente.setEnabled(false);
                txtProductos.setEnabled(false);
                txtVenta.setEnabled(false);
                txtEmpleado.setEnabled(false);
                txtPrecio.setEnabled(false);               

                break;
            case 3:
                btnBuscar.setVisible(false);
                btnBuscarH.setVisible(true);
                btnGuardar.setVisible(false);
                btnGuardarH.setVisible(false);
                btnEliminar.setVisible(false);                
                btnAñadir.setVisible(false);
                
                txtFecha.setEnabled(false);
                txtCantidad.setEnabled(false);
                txtSubtotal.setEnabled(false);
                txtVentaH.setEnabled(true);
                txtCliente.setEnabled(false);
                txtProductos.setEnabled(false);
                txtVenta.setEnabled(false);
                txtEmpleado.setEnabled(false);
                txtPrecio.setEnabled(false);

                break;
            case 4:
                btnEliminar.setVisible(false);
                btnBuscarH.setVisible(true);
                btnBuscar.setVisible(false);
                btnGuardar.setVisible(false);
                btnGuardarH.setVisible(false);
                btnAñadir.setVisible(false);
                
                txtFecha.setEnabled(false);
                txtCantidad.setEnabled(false);
                txtSubtotal.setEnabled(false);
                txtVentaH.setEnabled(true);
                txtCliente.setEnabled(false);
                txtProductos.setEnabled(false);
                txtVenta.setEnabled(false);
                txtEmpleado.setEnabled(false);
                txtPrecio.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVentaH = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtVenta = new javax.swing.JTextField();
        txtProductos = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnBuscarH = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardarH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setText("Clave de la Venta:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel2.setText("Clave del Cliente:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel3.setText("Fecha de la Venta:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel4.setText("Clave de la Venta:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel5.setText("Precio Total de la Venta:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel6.setText("Clave del Productos:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel7.setText("Cantidad de Productos:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel8.setText("Subtotal:");

        txtVentaH.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtVentaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentaHActionPerformed(evt);
            }
        });

        txtCliente.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        txtEmpleado.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoActionPerformed(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        txtVenta.setEditable(false);
        txtVenta.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentaActionPerformed(evt);
            }
        });

        txtProductos.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductosActionPerformed(evt);
            }
        });

        txtSubtotal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        txtCantidad.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ventas");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnBuscarH.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnBuscarH.setText("Buscar");
        btnBuscarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel10.setText("Encabezado de la Venta");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel11.setText("Venta");

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAñadir.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel12.setText("Clave del Empleado");

        txtPrecio.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        btnGuardarH.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnGuardarH.setText("Guardar");
        btnGuardarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(144, 144, 144)
                                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtVentaH, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                                .addComponent(txtCliente)
                                                .addComponent(txtEmpleado)
                                                .addComponent(txtFecha)
                                                .addComponent(txtPrecio))
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnBuscarH, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                    .addComponent(btnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(btnGuardarH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 104, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVentaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegresar))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVentaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentaHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentaHActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentaActionPerformed

    private void txtProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductosActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        String venta = validacionClave(txtVentaH.getText(), "Clave Venta", "v-", 4);       
        String producto = validacionClave(txtProductos.getText(),"Clave del producto", "po-", 5);
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        if(!(venta == "no" || producto == "no")){
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;database=GestionCajetas;user=user; "
                        + "password = 123;encrypt=true;trustServerCertificate=true;";
                Connection conect = DriverManager.getConnection(connectionUrl);
                stmt = conect.prepareStatement("select ClaveVenta from Ventas where ClaveVenta = '" + venta + "'");
                rs = stmt.executeQuery();
                if(!rs.next()){
                    System.out.println("Asd");
                }   else    {
                    stmt = conect.prepareStatement("select * from Ventas where ClaveVenta = '" + venta + "' and ClaveProd = '" + producto + "'");
                    rs = stmt.executeQuery();
                    while(rs.next()) {
                        for (int y=1;y<=rs.getMetaData().getColumnCount();y++){
                            switch(y){
                                case 2:
                                    txtProductos.setText(rs.getString(y));
                                    break;
                                case 3:    
                                    txtCantidad.setText(String.valueOf(rs.getInt(y)));
                                    break;
                                case 4:    
                                    txtSubtotal.setText(String.valueOf(rs.getFloat(y)));
                                    break;
                            }
                        }
                    }  
                    if(caso == 3){
                        btnGuardar.setVisible(true);
                        txtCantidad.setEnabled(true);
                        txtSubtotal.setEnabled(true);
                    }        
                }       
            } 
            catch (SQLException ex) 
            {
                System.out.println("Error." + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHActionPerformed
        // TODO add your handling code here:
        
        String venta = validacionClave(txtVentaH.getText(), "Clave Venta", "v-", 4);        
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;database=GestionCajetas;user=user; "
                        + "password = 123;encrypt=true;trustServerCertificate=true;";
                Connection conect = DriverManager.getConnection(connectionUrl);
                stmt = conect.prepareStatement("select ClaveVenta from Encabezado_Ventas where ClaveVenta = '" + venta + "'");
                rs = stmt.executeQuery();
                if(!rs.next()){
                    System.out.println("Asd");
                }   else    {
                    txtVenta.setText(txtVentaH.getText());
                    stmt = conect.prepareStatement("select * from Encabezado_Ventas where ClaveVenta = '" + venta + "'");
                    rs = stmt.executeQuery();
                    while(rs.next()) {
                        for (int y=1;y<=rs.getMetaData().getColumnCount();y++){
                            switch(y){
                                case 2:
                                    txtEmpleado.setText(rs.getString(y));
                                    break;
                                case 3:                                      
                                    txtCliente.setText(rs.getString(y));
                                    break;
                                case 4:                                        
                                    txtFecha.setText(rs.getString(y));
                                    break;
                                case 5:
                                    txtPrecio.setText(rs.getString(y));
                                
                            }
                        }
                    }                                        
                    switch(caso){
                        case 1:
                            txtCliente.setEnabled(false);
                            txtFecha.setEnabled(false);
                            txtEmpleado.setEnabled(false);
                            txtPrecio.setEnabled(false);
                            
                            txtProductos.setEnabled(true);
                            txtCantidad.setEnabled(true);
                            txtSubtotal.setEnabled(true);

                            btnGuardar.setVisible(true);
                            btnGuardarH.setVisible(false);
                            break;
                        case 2:
                            txtProductos.setEnabled(true);

                            btnBuscar.setVisible(true);                          
                            break;
                        case 3:
                            txtCliente.setEnabled(true);
                            txtFecha.setEnabled(true);
                            txtEmpleado.setEnabled(true);
                            txtPrecio.setEnabled(true);
                            
                            txtProductos.setEnabled(true);
                            txtCantidad.setEnabled(false);
                            txtSubtotal.setEnabled(false);

                            btnBuscar.setVisible(true);
                            btnGuardar.setVisible(false);
                            btnGuardarH.setVisible(true);
                            break;
                        case 4:
                            txtCliente.setEnabled(false);
                            txtFecha.setEnabled(false);
                            txtEmpleado.setEnabled(false);
                            txtPrecio.setEnabled(false);
                            
                            txtProductos.setEnabled(true);
                            txtCantidad.setEnabled(false);
                            txtSubtotal.setEnabled(false);

                            btnBuscar.setVisible(true);
                            btnEliminar.setVisible(true);
                    }                    
                }       
            } 
            catch (SQLException ex) 
            {
                System.out.println("Error." + ex.getMessage());
            } 
        
    }//GEN-LAST:event_btnBuscarHActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
        super.dispose();
        GestorVentas gv = new GestorVentas();
        gv.setVisible(true);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement stmt = null;
        ResultSet rs = null;
        try {
            String connectionUrl = "jdbc:sqlserver://localhost:1433;database=GestionCajetas;user=user; "
                    + "password = 123;encrypt=true;trustServerCertificate=true;";
            Connection conect = DriverManager.getConnection(connectionUrl);
            for(int i = 1; i<99; i ++){
                if(i < 10){
                    stmt = conect.prepareStatement("SELECT ClaveVenta FROM Encabezado_Ventas where ClaveVenta = 'v-0" + i + "'");
                    rs = stmt.executeQuery();
                    if(!rs.next()){
                        txtVentaH.setText("v-0" + i);
                        txtVenta.setText("v-0" + i);
                        break;
                    }
                }   else    {
                    stmt = conect.prepareStatement("SELECT ClaveVenta FROM Encabezado_Ventas where ClaveVenta = 'v-" + i + "'");
                    rs = stmt.executeQuery();
                    if(!rs.next()){
                        txtVentaH.setText("v-" + i);
                        txtVenta.setText("v-" + i);
                        break;
                    }

                }
            }
            txtCliente.setEnabled(true);
            txtFecha.setEnabled(true);
            txtEmpleado.setEnabled(true);
            txtPrecio.setEnabled(true);
            
            btnGuardarH.setVisible(true);
        } 
        catch (SQLException ex) 
        {
          System.out.println("Error." + ex.getMessage());
        }  
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnGuardarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHActionPerformed
        // TODO add your handling code here:
        String venta = validacionClave(txtVentaH.getText(), "Clave de la Venta", "v-", 4);
        String cliente = validacionClave(txtCliente.getText(), "Clave del Cliente", "cl-", 5);
        String empleado = validacionClave(txtEmpleado.getText(),"Clave del Empleado", "e-", 4);
        String fecha = validacionFecha(txtFecha.getText(), "Fecha de la Compra");
        float precio = validacionFloat(txtPrecio.getText(), "Precio de la venta", 4,2);
        PreparedStatement stmt = null;
        if(!(venta == "no" || cliente == "no" || fecha == "no" || empleado == "no" || precio == -1.001)){
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;database=GestionCajetas;user=user; "
                        + "password = 123;encrypt=true;trustServerCertificate=true;";
                Connection conect = DriverManager.getConnection(connectionUrl);
                if(caso == 1){
                    txtProductos.setEnabled(true);
                    txtCantidad.setEnabled(true);
                    txtSubtotal.setEnabled(true);   

                    btnGuardar.setVisible(true);
                    stmt = conect.prepareStatement("insert into Encabezado_Ventas values('" + venta + "', '" + empleado +"', '" + cliente + "', '" + fecha + "', " + precio + ")");
                    stmt.executeQuery();
                }  else    {
                   stmt = conect.prepareStatement("update Encabezado_Ventas set ClaveEmpleado = '" + empleado +
                           "', ClaveCliente = '" + cliente + "', FechaVenta = '" + fecha + 
                           "', Total = " + precio + " where ClaveVenta = '" + venta + "'"
                           );
                   stmt.executeQuery();               
                }

            } 
            catch (SQLException ex) 
            {
              System.out.println("Error." + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnGuardarHActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        String venta = validacionClave(txtVentaH.getText(), "Clave de la Venta", "v-", 4);
        String producto = validacionClave(txtProductos.getText(),"Clave del producto", "po-", 5);
        int cantidad = validacionInt(txtCantidad.getText(), "Cantidad", 2);
        float subtotal = validacionFloat(txtSubtotal.getText(),"Subtotal", 4,2);
        PreparedStatement stmt = null;
        try {
            String connectionUrl = "jdbc:sqlserver://localhost:1433;database=GestionCajetas;user=user; "
                    + "password = 123;encrypt=true;trustServerCertificate=true;";
            Connection conect = DriverManager.getConnection(connectionUrl);
            if(caso == 1){
                stmt = conect.prepareStatement("insert into Ventas values('" + venta + "', '" + producto +"', " + cantidad + ", " + subtotal + ")");
                JOptionPane.showMessageDialog(null, "Venta ingresada con exito.");
                super.dispose();
                GestorVentas gestor = new GestorVentas();
                gestor.setVisible(true);
                stmt.executeQuery();               
            }  else    {
               stmt = conect.prepareStatement("update Ventas set CantidadProd = " + cantidad + ", Subtotal = " 
                       + subtotal + " where ClaveProd = '" + producto + "' and ClaveVenta = '" + venta + "'"
                       );
               JOptionPane.showMessageDialog(null, "Venta modificada con exito.");
               stmt.executeQuery();               
            }
              
        } 
        catch (SQLException ex) 
        {
            System.out.println("Error." + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement stmt = null;
        String venta = txtVentaH.getText();

        try {
            String connectionUrl = "jdbc:sqlserver://localhost:1433;database=GestionCajetas;user=user; "
                    + "password = 123;encrypt=true;trustServerCertificate=true;";
            Connection conect = DriverManager.getConnection(connectionUrl);
                stmt = conect.prepareStatement("Delete FROM Ventas where ClaveVenta = '" + venta + "'");
                stmt.executeQuery();
              
        } 
        catch (SQLException ex) 
        {
            System.out.println("Error." + ex.getMessage());
            try {
                String connectionUrl = "jdbc:sqlserver://localhost:1433;database=GestionCajetas;user=user; "
                        + "password = 123;encrypt=true;trustServerCertificate=true;";
                Connection conect = DriverManager.getConnection(connectionUrl);

                    stmt = conect.prepareStatement("Delete FROM Encabezado_Ventas where ClaveVenta = '" + venta + "'");
                    JOptionPane.showMessageDialog(null, "Venta cancelada con éxito.");
                super.dispose();
                GestorVentas gestor = new GestorVentas();
                gestor.setVisible(true);
                    stmt.executeQuery();       
            } 
            catch (SQLException e) 
            {
                System.out.println("Error." + ex.getMessage());
            } 
        } 
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static String validacionClave(String Cadena, String valor, String tipo, int caracteres){
        boolean validado = false;
        float num;
        if(Cadena.length()!= caracteres) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor para " + valor + ".");
            validado = false;
        } else if (Cadena.substring(0, tipo.length()).equals(tipo)) {
            for(int x = caracteres-2; x < Cadena.length(); x++){
                if(Cadena.charAt(x) >= '0' && Cadena.charAt(x) <= '9') {
                    validado = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese un valor correcto para " + valor + ".");
                    validado = false;
                    break;               
                }   
            }  
        }
        if (validado) {
            return Cadena;
        }
        return "no";
    }
    
    public static String validacionTexto(String Cadena, String valor, int caracteres, boolean gato, boolean numeros){
        boolean validado = false;
        if(Cadena.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor para " + valor + ".");
            validado = false;
        } else if (Cadena.length() >= caracteres) {
            JOptionPane.showMessageDialog(null, "Ingrese dentro del rango establecido para " + valor + ".");
            validado = false;
            return "no";
        }
        for(int x = 0; x < Cadena.length(); x++){
            int num = (int) Cadena.charAt(x);
            if(((num >= 97 && num <= 122) || (num >= 65 && num <= 90)) || (Cadena.charAt(x) == '#' && gato) || ((Cadena.charAt(x) >= '0' && Cadena.charAt(x) <= '9')&&(numeros))) {
                validado = true;
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un valor correcto para " + valor + ".");
                validado = false;
                break;               
            }
        }  
        if (validado) {
            return Cadena;
        }
        return "no";
    }
    
    public static String validacionFecha(String Cadena, String valor) {
        boolean validado = false, mesListo = false, diaListo = false, noPasar = false;
        int mes = 0, limDia = 0, dia = 0;
        if(Cadena.length()!= 10) {
            JOptionPane.showMessageDialog(null, "Ingrese una fecha correcto para " + valor + ".");
            validado = false;
            System.out.println(1);
            return "no";
        }
        for(int x = 0; x < Cadena.length(); x++){
            if(mes<12 && mesListo == true){    
                if (x == 2 && (Cadena.charAt(x) == '/' || Cadena.charAt(x) == '-')) {
                    validado = true;
                    noPasar = true;
                } else if(x == 2) {
                    JOptionPane.showMessageDialog(null, "Ingrese una fecha correcto para " + valor + ".");
                    validado = false;
                    System.out.println(2);
                    return "no";
                }
                switch(mes){
                    case 1:
                        limDia = 31;
                        break;
                    case 2:
                        limDia = 28;
                        break;
                    case 3:
                        limDia = 31;
                        break;
                    case 4:
                        limDia = 30;
                        break;
                    case 5:
                        limDia = 31;
                        break;
                    case 6:
                        limDia = 30;
                        break;
                    case 7:
                        limDia = 31;
                        break;
                    case 8:
                        limDia = 31;
                        break;
                    case 9:
                        limDia = 30;
                        break;
                    case 10:
                        limDia = 31;
                        break;
                    case 11:
                        limDia = 30;
                        break;
                    case 12:
                        limDia = 31;
                        break;
                }
            } else if (mesListo == true) {
                JOptionPane.showMessageDialog(null, "Ingrese una mes correcto para " + valor + ".");
                validado = false;
                return "no";
            }
            
            if(dia<limDia && diaListo == true){    
                if (x == 5 && (Cadena.charAt(x) == '/' || Cadena.charAt(x) == '-')) {
                    validado = true;
                    noPasar = true;
                } else if(x == 5) {
                    JOptionPane.showMessageDialog(null, "Ingrese una fecha correcto para " + valor + ".");
                    validado = false;
                    System.out.println(3);
                    return "no";
                }
            } else if (diaListo == true) {
                JOptionPane.showMessageDialog(null, "Ingrese una dia correcto para " + valor + ".");
                validado = false;
                return "no";
            }
            
            if(Cadena.charAt(x) >= '0' && Cadena.charAt(x) <= '9' && noPasar == false) {
                validado = true;
                if(x<2) {
                    mes += Integer.parseInt(Cadena.charAt(x) + "");
                    if(x == 0)
                        mes = mes*10;
                    else
                        mesListo = true;
                } else if (x<5) {
                    dia += Integer.parseInt(Cadena.charAt(x) + "");
                    if(x == 3)
                        dia = dia*10;
                    else
                        diaListo = true;
                }
            } else if(noPasar == false) {
                JOptionPane.showMessageDialog(null, "Ingrese una fecha correcto para " + valor + ".");
                validado = false;
                System.out.println(4);
                return "no";              
            }   
            noPasar = false;
        }
        if (validado) {
            return Cadena;
        }
        return "no";
    }

    public static float validacionFloat(String numeroCad, String valor, int limEnteros, int limDecimales){
        boolean validado = false, puntoEx = false;
        float num, contEnteros = 0, contDecimales = 0;
        if(numeroCad.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor para " + valor + ".");
            validado = false;
        }
        for(int x = 0; x < numeroCad.length(); x++){
            if(numeroCad.charAt(x) >= '0' && numeroCad.charAt(x) <= '9') {
                validado = true;
                if (puntoEx == false) {
                    contEnteros++;
                } else {
                    contDecimales++;
                }
            } else if(numeroCad.charAt(x) == '.' && puntoEx == false) {
                validado = true;
                puntoEx = true;
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un valor correcto para " + valor + ".");
                validado = false;
                puntoEx = false;
                break;               
            }
            if(contEnteros > limEnteros) {
                validado = false;
                break;
            } else if (contDecimales > limDecimales) {
                validado = false;
                break;
            }
        }  
        if (validado) {
            num = Float.parseFloat(numeroCad);
            return num;
        }
        return -1.001f;
    }
    
    public static int validacionInt(String numeroCad, String valor, int longitud){
        boolean validado = false;
        int num, cont = 0;
        if(numeroCad.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor para " + valor + ".");
            validado = false;
        }
        for(int x = 0; x < numeroCad.length(); x++){
            if(numeroCad.charAt(x) >= '0' && numeroCad.charAt(x) <= '9') {
                validado = true;
                cont++;
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un valor correcto para " + valor + ".");
                validado = false;
                break;               
            }
            if(cont > longitud) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor dentro del rango para " + valor + ".");
                validado = false;
                break;
            }
        }  
        if (validado) {
            num = Integer.parseInt(numeroCad);
            return num;
        }
        return -1;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasForm(caso).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarH;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarH;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProductos;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtVenta;
    private javax.swing.JTextField txtVentaH;
    // End of variables declaration//GEN-END:variables
}
